# Generated by Django 3.1.1 on 2022-10-05 15:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(blank=True, editable=False, help_text='Automatically Set After Save', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Course Title')),
                ('slug', models.SlugField(help_text='autofill after save.', unique=True, verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('publish', models.BooleanField(blank=True, default=False, help_text='Publish course?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(blank=True, editable=False, help_text='Automatically Set After Save', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Video Name')),
                ('thumb', models.ImageField(blank=True, help_text='Upload thumbnail image if available.', upload_to='course_thumb_uploads/', verbose_name='Thumbnail Image')),
                ('video', models.FileField(help_text='Upload course video.', upload_to='course_video_uploads/')),
                ('course', models.ForeignKey(blank=True, help_text='Select course', on_delete=django.db.models.deletion.CASCADE, related_name='video', to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
