# Generated by Django 3.1.1 on 2022-10-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20221006_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(blank=True, default=True, verbose_name='Completion Certificate'),
        ),
    ]
