# Generated by Django 3.1.1 on 2022-10-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rewards',
            field=models.BooleanField(blank=True, default=False, verbose_name='Enroll & Win Rewards'),
        ),
    ]
