# Generated by Django 3.1.1 on 2022-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, 'Beginner Level'), (2, 'Medium Level'), (3, 'Expert Level')], default=1),
        ),
    ]
