# Generated by Django 3.1.1 on 2022-10-06 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text='Ex.: 4 Hrs', max_length=255, null=True, verbose_name='Course Duration in Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Beginner Level'), (2, 'Medium Level'), (3, 'Expert Level')], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(blank=True, default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
