# Generated by Django 3.1.1 on 2022-10-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='created_on',
        ),
    ]
