# Generated by Django 3.2 on 2022-10-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
