# Generated by Django 3.2 on 2022-10-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_course_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['created_on']},
        ),
    ]
