# Generated by Django 3.2 on 2022-10-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_topic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='courses.topic'),
        ),
    ]
