# Generated by Django 3.2 on 2022-10-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, default='Saloon', max_length=255, verbose_name='Site Title')),
                ('icon', models.ImageField(help_text='Recommended Size: 96x96 Pixels', upload_to='site_settings_icon_uploads/', verbose_name='Site Favicon')),
                ('logo', models.ImageField(help_text='Recommended Size: 120x75 Pixels', upload_to='site_settings_logo_uploads/', verbose_name='Site Logo')),
                ('email', models.EmailField(blank=True, default='contact@gmail.com', max_length=254, verbose_name='E-Mail Address')),
                ('phone', models.CharField(blank=True, default='+91 99999 99999', max_length=15, verbose_name='Mobile No.')),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
