# Generated by Django 3.2 on 2022-10-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='about_us',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut tur incidunt ut labore et.', verbose_name='About Us Short Description'),
        ),
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.TextField(blank=True, default='Our Address', verbose_name='Office Address'),
        ),
        migrations.AddField(
            model_name='settings',
            name='logo_white',
            field=models.ImageField(blank=True, help_text='White color logo.Recommended Size: 150x90 Pixels', upload_to='site_settings_logo_uploads/', verbose_name='Site Logo White'),
        ),
        migrations.AddField(
            model_name='settings',
            name='office_open',
            field=models.CharField(blank=True, default='Sun - Fri (08AM - 10PM)', max_length=255, verbose_name='Office Open'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='icon',
            field=models.ImageField(blank=True, help_text='Recommended Size: 96x96 Pixels', upload_to='site_settings_icon_uploads/', verbose_name='Site Favicon'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Recommended Size: 150x90 Pixels', upload_to='site_settings_logo_uploads/', verbose_name='Site Logo'),
        ),
    ]
