# Generated by Django 3.2 on 2022-10-19 10:39

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20221018_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(blank=True, editable=False, help_text='Automatically Set After Save', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Mobile No.')),
                ('person', models.PositiveIntegerField(choices=[(1, '1 Person'), (2, '2 Person'), (3, '3 Person'), (4, '4 Person'), (5, '5 Person'), (6, '6 Person'), (7, '7 Person')], default=2, verbose_name='Person')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
